<Project Sdk="Godot.NET.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <RootNamespace>Game</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sim\Sim.csproj" />
  </ItemGroup>
</Project>
