using Godot;

namespace Game;

/// The four noises the game makes.
///
/// It made none at all until now, which is a strange thing for a factory game:
/// the genre's whole pleasure is a rhythm you can hear settle into place, and
/// this one was silent whether you succeeded or failed. Four sounds is not an
/// audio design -- it is the floor. What it buys is that every action the
/// player takes now answers back, and a refusal sounds like a refusal without
/// the player having to read the toast.
///
/// They are generated by `tools/generate_audio.py` and committed, for the same
/// reason the models and the icon atlas are: the build has to be reproducible
/// from the repository alone.
public sealed partial class Sounds : Node
{
    public enum Cue { Dig, Place, Deliver, Refuse }

    private readonly System.Collections.Generic.Dictionary<Cue, AudioStream?> _streams = new();
    private AudioStreamPlayer[] _voices = System.Array.Empty<AudioStreamPlayer>();
    private int _next;

    /// Several players, cycled. One player restarts itself when a second cue
    /// lands in the same breath -- and cues land in the same breath constantly
    /// here, because a click can dig, refuse and advance a step at once.
    private const int Voices = 6;

    public override void _Ready()
    {
        foreach (var cue in System.Enum.GetValues<Cue>())
        {
            var path = $"res://audio/{cue.ToString().ToLowerInvariant()}.wav";
            _streams[cue] = ResourceLoader.Exists(path)
                ? ResourceLoader.Load<AudioStream>(path)
                : null;
        }

        _voices = new AudioStreamPlayer[Voices];
        for (var i = 0; i < Voices; i++)
        {
            _voices[i] = new AudioStreamPlayer { Name = $"Voice{i}", VolumeDb = -8f };
            AddChild(_voices[i]);
        }
    }

    /// Plays one cue. Silently does nothing when the file is missing or the
    /// machine has no audio at all -- a headless run has a dummy driver, and a
    /// missing sound must never be the reason a build fails to start.
    public void Play(Cue cue)
    {
        if (_voices.Length == 0) return;
        if (!_streams.TryGetValue(cue, out var stream) || stream is null) return;

        var voice = _voices[_next];
        _next = (_next + 1) % _voices.Length;
        voice.Stream = stream;
        voice.Play();
    }

    /// Whether a cue actually resolved to a file, for the headless report. A
    /// sound that silently did not load is indistinguishable from a game with
    /// no sound, which is what this used to be.
    public int Loaded
    {
        get
        {
            var n = 0;
            foreach (var stream in _streams.Values)
                if (stream is not null) n++;
            return n;
        }
    }
}
